title: Giovani Nascimento Pereira # your site title
author: Giovani Nascimento Pereira
email: giovani.x.pereira@gmail.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  iOS Developer. Computer Engineering Student at Unicamp, and student at Apple Developer Academy @ Instituto Eldorado
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://giovaninppc.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  giovaninppc # replace with your_github_username or comment to remove link from footer
instagram_username: giovaninppc # replace with your_instagram_username or comment to remove link from footer
social:
  name: Giovani Nascimento Pereira
  links:
    - https://www.facebook.com/giovaninppc
    - https://www.linkedin.com/in/giovaninppc
    - https://github.com/giovaninppc

disqus:
  shortname: giovaninppc # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
