# SITE CONFIGURATION
title: Giovani Nascimento Pereira # your site title
author: Giovani Nascimento Pereira # You :P
description: > # Meta description of Homepage
  iOS Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://giovaninppc.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Giovani Nascimento Pereira
  links:
    - https://twitter.com/
    - https://www.facebook.com/giovaninppc
    - https://www.linkedin.com/in/giovaninppc
    - https://plus.google.com/+giovaninppc
    - https://github.com/giovaninppc
    - https://keybase.io/

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Portifolio', link: '/portifolio'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  iOS Developer. Computer Engineering Student at Unicamp, and student at Apple Developer Academy @ Instituto Eldorado.
  I'm here to talk about my projects and apps,
  Share some things I've learned,
  and maybe learn some new things too 
  =]

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: giovani.x.pereira@gmail.com # email for form submission

#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  giovaninppc # replace with your_github_username or comment to remove link from footer
instagram_username: giovaninppc # replace with your_instagram_username or comment to remove link from footer
facebook_username: giovaninppc

disqus:
  shortname: giovaninppc # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
